# Generated by Django 4.0.3 on 2022-03-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startfriendship',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
